### ISSUE TITLE
Can't change underline color

### ISSUE THREAD

**Issue by vandevelde-jacob** [johnotander/atom-underline-trailing-whitespace#4]
Howdy,

Tired all of the following styles, none are working. I looked at the closed issues and saw the "underline-trailing-whitespace" so I tried that too.

Styles tried:

``` less
.trailing-whitespace {
    border-bottom-color: cyan;
}

trailing-whitespace {
    border-bottom-color: purple;
}

underline-trailing-whitespace {
  border-bottom-color: green;
}

.underline-trailing-whitespace {
  border-bottom-color: red;
}
```

I closed the tabs and Atom after changing the styles.

I've only installed Atom today, hopefully it's just me doing something stupid. I'm modifying the /home/Username/.atom/styles.less file.

Cheers.

**Comment by johno** [comment]
Hello!

My apologies, I neglected to update the readme after the latest API changes with atom, the following should work:

``` css
atom-text-editor,
atom-text-editor::shadow  {

  .trailing-whitespace {
    border-bottom-color: @my-new-color;
  }
}
```

Let me know if you have any more questions : )
